[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[redirects]]
  from = "/"
  to = "/en"
  status = 302
  force = true

[[redirects]]
  from = "/en/*"
  to = "/en/:splat"
  status = 200

[[redirects]]
  from = "/ta/*"
  to = "/ta/:splat"
  status = 200

[[redirects]]
  from = "/hi/*"
  to = "/hi/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "*.mp4"
  [headers.values]
    Content-Type = "video/mp4"
    Cache-Control = "public, max-age=31536000"
