// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[locale]" | "/[locale]/internship" | "/[locale]/internship/basic-info" | "/[locale]/internship/consent" | "/[locale]/internship/fairness" | "/[locale]/internship/preferences" | "/[locale]/internship/recommendations" | "/[locale]/internship/results" | "/[locale]/internship/resume" | "/[locale]/internship/skills" | "/admin" | "/admin/reports" | "/api-demo" | "/api-test" | "/copilot" | "/copilot/integrations" | "/copilot/review" | "/copilot/settings/privacy" | "/dashboard" | "/login" | "/offline" | "/profile" | "/register"
type AppRouteHandlerRoutes = "/api/admin/analytics" | "/api/admin/reports" | "/api/ai/assistant" | "/api/ats/inspect" | "/api/auth/[...nextauth]" | "/api/auth/register" | "/api/auth/users" | "/api/batch/create" | "/api/batch/export" | "/api/batch/ingest" | "/api/batch/run" | "/api/batch/status" | "/api/batch/webhook" | "/api/coach/tailor" | "/api/dsr/delete" | "/api/feedback/comment" | "/api/feedback/share" | "/api/integrations/google/callback" | "/api/integrations/google/start" | "/api/interview/structure" | "/api/jd/parse" | "/api/jobs/retention" | "/api/jobs/rollup" | "/api/parse-resume" | "/api/push/draft" | "/api/referrals/import" | "/api/referrals/intro" | "/api/referrals/list" | "/api/resume/draft" | "/api/resume/generate"
type PageRoutes = never
type LayoutRoutes = "/" | "/[locale]" | "/[locale]/internship"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[locale]": { "locale": string; }
  "/[locale]/internship": { "locale": string; }
  "/[locale]/internship/basic-info": { "locale": string; }
  "/[locale]/internship/consent": { "locale": string; }
  "/[locale]/internship/fairness": { "locale": string; }
  "/[locale]/internship/preferences": { "locale": string; }
  "/[locale]/internship/recommendations": { "locale": string; }
  "/[locale]/internship/results": { "locale": string; }
  "/[locale]/internship/resume": { "locale": string; }
  "/[locale]/internship/skills": { "locale": string; }
  "/admin": {}
  "/admin/reports": {}
  "/api-demo": {}
  "/api-test": {}
  "/api/admin/analytics": {}
  "/api/admin/reports": {}
  "/api/ai/assistant": {}
  "/api/ats/inspect": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/auth/register": {}
  "/api/auth/users": {}
  "/api/batch/create": {}
  "/api/batch/export": {}
  "/api/batch/ingest": {}
  "/api/batch/run": {}
  "/api/batch/status": {}
  "/api/batch/webhook": {}
  "/api/coach/tailor": {}
  "/api/dsr/delete": {}
  "/api/feedback/comment": {}
  "/api/feedback/share": {}
  "/api/integrations/google/callback": {}
  "/api/integrations/google/start": {}
  "/api/interview/structure": {}
  "/api/jd/parse": {}
  "/api/jobs/retention": {}
  "/api/jobs/rollup": {}
  "/api/parse-resume": {}
  "/api/push/draft": {}
  "/api/referrals/import": {}
  "/api/referrals/intro": {}
  "/api/referrals/list": {}
  "/api/resume/draft": {}
  "/api/resume/generate": {}
  "/copilot": {}
  "/copilot/integrations": {}
  "/copilot/review": {}
  "/copilot/settings/privacy": {}
  "/dashboard": {}
  "/login": {}
  "/offline": {}
  "/profile": {}
  "/register": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/[locale]": never
  "/[locale]/internship": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
