// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/dist/lib/metadata/types/metadata-interface.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/[locale]/internship/basic-info/page.tsx
{
  const handler = {} as typeof import("../../src/app/[locale]/internship/basic-info/page.js")
  handler satisfies AppPageConfig<"/[locale]/internship/basic-info">
}

// Validate ../../src/app/[locale]/internship/consent/page.tsx
{
  const handler = {} as typeof import("../../src/app/[locale]/internship/consent/page.js")
  handler satisfies AppPageConfig<"/[locale]/internship/consent">
}

// Validate ../../src/app/[locale]/internship/fairness/page.tsx
{
  const handler = {} as typeof import("../../src/app/[locale]/internship/fairness/page.js")
  handler satisfies AppPageConfig<"/[locale]/internship/fairness">
}

// Validate ../../src/app/[locale]/internship/page.tsx
{
  const handler = {} as typeof import("../../src/app/[locale]/internship/page.js")
  handler satisfies AppPageConfig<"/[locale]/internship">
}

// Validate ../../src/app/[locale]/internship/preferences/page.tsx
{
  const handler = {} as typeof import("../../src/app/[locale]/internship/preferences/page.js")
  handler satisfies AppPageConfig<"/[locale]/internship/preferences">
}

// Validate ../../src/app/[locale]/internship/recommendations/page.tsx
{
  const handler = {} as typeof import("../../src/app/[locale]/internship/recommendations/page.js")
  handler satisfies AppPageConfig<"/[locale]/internship/recommendations">
}

// Validate ../../src/app/[locale]/internship/results/page.tsx
{
  const handler = {} as typeof import("../../src/app/[locale]/internship/results/page.js")
  handler satisfies AppPageConfig<"/[locale]/internship/results">
}

// Validate ../../src/app/[locale]/internship/resume/page.tsx
{
  const handler = {} as typeof import("../../src/app/[locale]/internship/resume/page.js")
  handler satisfies AppPageConfig<"/[locale]/internship/resume">
}

// Validate ../../src/app/[locale]/internship/skills/page.tsx
{
  const handler = {} as typeof import("../../src/app/[locale]/internship/skills/page.js")
  handler satisfies AppPageConfig<"/[locale]/internship/skills">
}

// Validate ../../src/app/[locale]/page.tsx
{
  const handler = {} as typeof import("../../src/app/[locale]/page.js")
  handler satisfies AppPageConfig<"/[locale]">
}

// Validate ../../src/app/admin/page.tsx
{
  const handler = {} as typeof import("../../src/app/admin/page.js")
  handler satisfies AppPageConfig<"/admin">
}

// Validate ../../src/app/admin/reports/page.tsx
{
  const handler = {} as typeof import("../../src/app/admin/reports/page.js")
  handler satisfies AppPageConfig<"/admin/reports">
}

// Validate ../../src/app/api-demo/page.tsx
{
  const handler = {} as typeof import("../../src/app/api-demo/page.js")
  handler satisfies AppPageConfig<"/api-demo">
}

// Validate ../../src/app/api-test/page.tsx
{
  const handler = {} as typeof import("../../src/app/api-test/page.js")
  handler satisfies AppPageConfig<"/api-test">
}

// Validate ../../src/app/copilot/integrations/page.tsx
{
  const handler = {} as typeof import("../../src/app/copilot/integrations/page.js")
  handler satisfies AppPageConfig<"/copilot/integrations">
}

// Validate ../../src/app/copilot/page.tsx
{
  const handler = {} as typeof import("../../src/app/copilot/page.js")
  handler satisfies AppPageConfig<"/copilot">
}

// Validate ../../src/app/copilot/review/page.tsx
{
  const handler = {} as typeof import("../../src/app/copilot/review/page.js")
  handler satisfies AppPageConfig<"/copilot/review">
}

// Validate ../../src/app/copilot/settings/privacy/page.tsx
{
  const handler = {} as typeof import("../../src/app/copilot/settings/privacy/page.js")
  handler satisfies AppPageConfig<"/copilot/settings/privacy">
}

// Validate ../../src/app/dashboard/page.tsx
{
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  handler satisfies AppPageConfig<"/dashboard">
}

// Validate ../../src/app/login/page.tsx
{
  const handler = {} as typeof import("../../src/app/login/page.js")
  handler satisfies AppPageConfig<"/login">
}

// Validate ../../src/app/offline/page.tsx
{
  const handler = {} as typeof import("../../src/app/offline/page.js")
  handler satisfies AppPageConfig<"/offline">
}

// Validate ../../src/app/page.tsx
{
  const handler = {} as typeof import("../../src/app/page.js")
  handler satisfies AppPageConfig<"/">
}

// Validate ../../src/app/profile/page.tsx
{
  const handler = {} as typeof import("../../src/app/profile/page.js")
  handler satisfies AppPageConfig<"/profile">
}

// Validate ../../src/app/register/page.tsx
{
  const handler = {} as typeof import("../../src/app/register/page.js")
  handler satisfies AppPageConfig<"/register">
}

// Validate ../../src/app/api/admin/analytics/route.ts
{
  const handler = {} as typeof import("../../src/app/api/admin/analytics/route.js")
  handler satisfies RouteHandlerConfig<"/api/admin/analytics">
}

// Validate ../../src/app/api/admin/reports/route.ts
{
  const handler = {} as typeof import("../../src/app/api/admin/reports/route.js")
  handler satisfies RouteHandlerConfig<"/api/admin/reports">
}

// Validate ../../src/app/api/ai/assistant/route.ts
{
  const handler = {} as typeof import("../../src/app/api/ai/assistant/route.js")
  handler satisfies RouteHandlerConfig<"/api/ai/assistant">
}

// Validate ../../src/app/api/ats/inspect/route.ts
{
  const handler = {} as typeof import("../../src/app/api/ats/inspect/route.js")
  handler satisfies RouteHandlerConfig<"/api/ats/inspect">
}

// Validate ../../src/app/api/auth/[...nextauth]/route.ts
{
  const handler = {} as typeof import("../../src/app/api/auth/[...nextauth]/route.js")
  handler satisfies RouteHandlerConfig<"/api/auth/[...nextauth]">
}

// Validate ../../src/app/api/auth/register/route.ts
{
  const handler = {} as typeof import("../../src/app/api/auth/register/route.js")
  handler satisfies RouteHandlerConfig<"/api/auth/register">
}

// Validate ../../src/app/api/auth/users/route.ts
{
  const handler = {} as typeof import("../../src/app/api/auth/users/route.js")
  handler satisfies RouteHandlerConfig<"/api/auth/users">
}

// Validate ../../src/app/api/batch/create/route.ts
{
  const handler = {} as typeof import("../../src/app/api/batch/create/route.js")
  handler satisfies RouteHandlerConfig<"/api/batch/create">
}

// Validate ../../src/app/api/batch/export/route.ts
{
  const handler = {} as typeof import("../../src/app/api/batch/export/route.js")
  handler satisfies RouteHandlerConfig<"/api/batch/export">
}

// Validate ../../src/app/api/batch/ingest/route.ts
{
  const handler = {} as typeof import("../../src/app/api/batch/ingest/route.js")
  handler satisfies RouteHandlerConfig<"/api/batch/ingest">
}

// Validate ../../src/app/api/batch/run/route.ts
{
  const handler = {} as typeof import("../../src/app/api/batch/run/route.js")
  handler satisfies RouteHandlerConfig<"/api/batch/run">
}

// Validate ../../src/app/api/batch/status/route.ts
{
  const handler = {} as typeof import("../../src/app/api/batch/status/route.js")
  handler satisfies RouteHandlerConfig<"/api/batch/status">
}

// Validate ../../src/app/api/batch/webhook/route.ts
{
  const handler = {} as typeof import("../../src/app/api/batch/webhook/route.js")
  handler satisfies RouteHandlerConfig<"/api/batch/webhook">
}

// Validate ../../src/app/api/coach/tailor/route.ts
{
  const handler = {} as typeof import("../../src/app/api/coach/tailor/route.js")
  handler satisfies RouteHandlerConfig<"/api/coach/tailor">
}

// Validate ../../src/app/api/dsr/delete/route.ts
{
  const handler = {} as typeof import("../../src/app/api/dsr/delete/route.js")
  handler satisfies RouteHandlerConfig<"/api/dsr/delete">
}

// Validate ../../src/app/api/feedback/comment/route.ts
{
  const handler = {} as typeof import("../../src/app/api/feedback/comment/route.js")
  handler satisfies RouteHandlerConfig<"/api/feedback/comment">
}

// Validate ../../src/app/api/feedback/share/route.ts
{
  const handler = {} as typeof import("../../src/app/api/feedback/share/route.js")
  handler satisfies RouteHandlerConfig<"/api/feedback/share">
}

// Validate ../../src/app/api/integrations/google/callback/route.ts
{
  const handler = {} as typeof import("../../src/app/api/integrations/google/callback/route.js")
  handler satisfies RouteHandlerConfig<"/api/integrations/google/callback">
}

// Validate ../../src/app/api/integrations/google/start/route.ts
{
  const handler = {} as typeof import("../../src/app/api/integrations/google/start/route.js")
  handler satisfies RouteHandlerConfig<"/api/integrations/google/start">
}

// Validate ../../src/app/api/interview/structure/route.ts
{
  const handler = {} as typeof import("../../src/app/api/interview/structure/route.js")
  handler satisfies RouteHandlerConfig<"/api/interview/structure">
}

// Validate ../../src/app/api/jd/parse/route.ts
{
  const handler = {} as typeof import("../../src/app/api/jd/parse/route.js")
  handler satisfies RouteHandlerConfig<"/api/jd/parse">
}

// Validate ../../src/app/api/jobs/retention/route.ts
{
  const handler = {} as typeof import("../../src/app/api/jobs/retention/route.js")
  handler satisfies RouteHandlerConfig<"/api/jobs/retention">
}

// Validate ../../src/app/api/jobs/rollup/route.ts
{
  const handler = {} as typeof import("../../src/app/api/jobs/rollup/route.js")
  handler satisfies RouteHandlerConfig<"/api/jobs/rollup">
}

// Validate ../../src/app/api/parse-resume/route.ts
{
  const handler = {} as typeof import("../../src/app/api/parse-resume/route.js")
  handler satisfies RouteHandlerConfig<"/api/parse-resume">
}

// Validate ../../src/app/api/push/draft/route.ts
{
  const handler = {} as typeof import("../../src/app/api/push/draft/route.js")
  handler satisfies RouteHandlerConfig<"/api/push/draft">
}

// Validate ../../src/app/api/referrals/import/route.ts
{
  const handler = {} as typeof import("../../src/app/api/referrals/import/route.js")
  handler satisfies RouteHandlerConfig<"/api/referrals/import">
}

// Validate ../../src/app/api/referrals/intro/route.ts
{
  const handler = {} as typeof import("../../src/app/api/referrals/intro/route.js")
  handler satisfies RouteHandlerConfig<"/api/referrals/intro">
}

// Validate ../../src/app/api/referrals/list/route.ts
{
  const handler = {} as typeof import("../../src/app/api/referrals/list/route.js")
  handler satisfies RouteHandlerConfig<"/api/referrals/list">
}

// Validate ../../src/app/api/resume/draft/route.ts
{
  const handler = {} as typeof import("../../src/app/api/resume/draft/route.js")
  handler satisfies RouteHandlerConfig<"/api/resume/draft">
}

// Validate ../../src/app/api/resume/generate/route.ts
{
  const handler = {} as typeof import("../../src/app/api/resume/generate/route.js")
  handler satisfies RouteHandlerConfig<"/api/resume/generate">
}





// Validate ../../src/app/[locale]/internship/layout.tsx
{
  const handler = {} as typeof import("../../src/app/[locale]/internship/layout.js")
  handler satisfies LayoutConfig<"/[locale]/internship">
}

// Validate ../../src/app/[locale]/layout.tsx
{
  const handler = {} as typeof import("../../src/app/[locale]/layout.js")
  handler satisfies LayoutConfig<"/[locale]">
}

// Validate ../../src/app/layout.tsx
{
  const handler = {} as typeof import("../../src/app/layout.js")
  handler satisfies LayoutConfig<"/">
}
