var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/profile/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__db9d2cb1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_d0b0ee8f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_d50383c3._.js")
R.c("server/chunks/ssr/node_modules_a6977744._.js")
R.c("server/chunks/ssr/src_app_ca777385._.js")
R.c("server/chunks/ssr/[root-of-the-server]__8c7ede40._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__9d139612._.js")
R.c("server/chunks/ssr/_f57231f2._.js")
R.c("server/chunks/ssr/_9e7639f3._.js")
R.m(510519)
R.m(124403)
module.exports=R.m(124403).exports
