var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/interview/structure/route.js")
R.c("server/chunks/[root-of-the-server]__e2720c97._.js")
R.c("server/chunks/src_lib_ai_ts_d1d17df9._.js")
R.c("server/chunks/node_modules_next_d739b5ba._.js")
R.c("server/chunks/node_modules_next_dist_2fde623e._.js")
R.c("server/chunks/[root-of-the-server]__a6cbd1f2._.js")
R.c("server/chunks/_c14ee14b._.js")
R.c("server/chunks/node_modules_zod_v3_external_d1e61c8a.js")
R.m(322285)
R.m(863967)
module.exports=R.m(863967).exports
