var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/login/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__db9d2cb1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_d0b0ee8f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_d50383c3._.js")
R.c("server/chunks/ssr/node_modules_a6977744._.js")
R.c("server/chunks/ssr/src_app_ca777385._.js")
R.c("server/chunks/ssr/[root-of-the-server]__8c7ede40._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__3deccce9._.js")
R.c("server/chunks/ssr/_f57231f2._.js")
R.c("server/chunks/ssr/_3a96fa12._.js")
R.m(473485)
R.m(760756)
module.exports=R.m(760756).exports
