var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/resume/draft/route.js")
R.c("server/chunks/[root-of-the-server]__350abd04._.js")
R.c("server/chunks/node_modules_zod_v3_external_d1e61c8a.js")
R.c("server/chunks/node_modules_next_d739b5ba._.js")
R.c("server/chunks/_c14ee14b._.js")
R.c("server/chunks/node_modules_next_dist_2fde623e._.js")
R.c("server/chunks/[root-of-the-server]__a6cbd1f2._.js")
R.c("server/chunks/src_lib_ai_ts_d1d17df9._.js")
R.m(497690)
R.m(470679)
module.exports=R.m(470679).exports
