var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/feedback/share/route.js")
R.c("server/chunks/[root-of-the-server]__1b3e6876._.js")
R.c("server/chunks/node_modules_d0ed682e._.js")
R.c("server/chunks/node_modules_next_d739b5ba._.js")
R.c("server/chunks/_c14ee14b._.js")
R.c("server/chunks/node_modules_next_dist_2fde623e._.js")
R.c("server/chunks/[root-of-the-server]__a6cbd1f2._.js")
R.c("server/chunks/node_modules_zod_v3_external_d1e61c8a.js")
R.m(825964)
R.m(350273)
module.exports=R.m(350273).exports
