var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/batch/create/route.js")
R.c("server/chunks/[root-of-the-server]__30c4de41._.js")
R.c("server/chunks/node_modules_zod_v3_external_d1e61c8a.js")
R.c("server/chunks/node_modules_next_d739b5ba._.js")
R.c("server/chunks/_c14ee14b._.js")
R.c("server/chunks/[root-of-the-server]__a6cbd1f2._.js")
R.c("server/chunks/node_modules_next_dist_2fde623e._.js")
R.m(838732)
R.m(899060)
module.exports=R.m(899060).exports
